Repository InfraBlockchain/infra-substrate, pull requests merged in 2023-03, with the labels that each got.

#9 create pr template
  PULL_REQUEST_TEMPLATE.md
Labels: documentation

#13 store a vote weight of each extrinsic for PoT
  bin/node-template/node/src/benchmarking.rs
  frame/proof-of-transaction/src/lib.rs
Labels: enhancement

#15 Refactoring pot pallet
  .github/dependabot.yml
  .github/pr-custom-review.yml
  .github/stale.yml
  .github/workflows/auto-label-issues.yml
  .github/workflows/burnin-label-notification.yml
  .github/workflows/check-D-labels.yml
  .github/workflows/check-labels.yml
  .github/workflows/md-link-check.yml
  .github/workflows/mlc_config.json
  .github/workflows/monthly-tag.yml
  .github/workflows/pr-custom-review.yml
  .github/workflows/release-bot.yml
  .github/workflows/release-tagging.yml
  Cargo.lock
  bin/node-template/node/src/benchmarking.rs
  bin/node-template/runtime/src/lib.rs
  frame/proof-of-transaction/Cargo.toml
  frame/proof-of-transaction/src/lib.rs
  frame/proof-of-transaction/src/mock.rs
  frame/proof-of-transaction/src/tests.rs
Labels: trivial

#16 implement api function for get_vote_info
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/proof-of-transaction/Cargo.toml
  frame/proof-of-transaction/runtime-api/Cargo.toml
  frame/proof-of-transaction/runtime-api/src/lib.rs
  frame/proof-of-transaction/src/lib.rs
  frame/proof-of-transaction/src/mock.rs
  frame/proof-of-transaction/src/tests.rs
Labels: enhancement
